# Generated by Django 3.1.2 on 2020-10-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('a_no', models.AutoField(primary_key=True, serialize=False)),
                ('a_title', models.CharField(max_length=255)),
                ('a_type', models.CharField(max_length=50)),
                ('a_note', models.CharField(max_length=4096, null=True)),
                ('a_image', models.CharField(max_length=1000, null=True)),
                ('a_count', models.IntegerField(default=0)),
                ('a_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('a_usage', models.CharField(max_length=10)),
            ],
        ),
    ]
