# Generated by Django 3.1.2 on 2020-10-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20201014_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='a_image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
