# Generated by Django 3.1.2 on 2020-10-15 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20201014_1416'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='album_album',
        ),
    ]
