# Generated by Django 3.1.2 on 2020-10-15 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20201015_0739'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='album',
        ),
    ]
